import { useMemo, useState } from "react";

const AGE_GROUPS = ["Young Kids (5–8)", "Tweens (9–12)", "Teens (13–17)"];
const PASSWORDS = { Staff: "FC2026Staff", Volunteer: "BuddyUp2026", Parent: "SunCircle26" };

const SEED_CHILDREN = [
  { id: 1, name: "Daniel", photo: "🎵", ageGroup: "Tweens (9–12)", interests: ["Music", "Swimming", "Running"], personality: "Very energetic and loves to move.", communication: "Keep things calm and predictable.", notes: "Loves numbers and counting games." },
  { id: 2, name: "Alan", photo: "🎧", ageGroup: "Young Kids (5–8)", interests: ["Sensory Play", "Quiet Activities"], personality: "Loves sensory experiences in low-stimulation spaces.", communication: "Speak softly and give him time to process.", notes: "Headphones nearby give him security." },
  { id: 3, name: "Noa", photo: "✨", ageGroup: "Teens (13–17)", interests: ["Social Connection", "Feeling Included"], personality: "Loves feeling cool and socially accepted.", communication: "Treat her like a peer and ask her opinions.", notes: "Let her lead the activity sometimes." },
  { id: 4, name: "Emma", photo: "🎨", ageGroup: "Tweens (9–12)", interests: ["Painting", "Conversation"], personality: "Lights up with direct one-on-one attention.", communication: "Talk to her, not around her.", notes: "Start a painting session." },
  { id: 5, name: "Sophie", photo: "✏️", ageGroup: "Young Kids (5–8)", interests: ["Drawing"], personality: "Sweet and creative; takes comfort in familiar people.", communication: "Use a gentle, calm approach.", notes: "Let her lead with drawing." },
  { id: 6, name: "Gabby", photo: "👸", ageGroup: "Young Kids (5–8)", interests: ["Singing", "Drawing", "Stickers"], personality: "Bubbly and talkative, with a love of princesses.", communication: "Give her a moment to shine before redirecting.", notes: "Stickers are an instant connection." },
  { id: 7, name: "Roman", photo: "🍪", ageGroup: "Tweens (9–12)", interests: ["Swimming", "Cookies", "Birthdays"], personality: "Relaxed and happiest with good company.", communication: "Keep the vibe chill.", notes: "Let him sort his cookies." },
  { id: 8, name: "Alex", photo: "🏃‍♀️", ageGroup: "Tweens (9–12)", interests: ["Painting", "Playground", "Swimming"], personality: "Super energetic and remembers birthdays.", communication: "Offer reminders to hydrate and share.", notes: "Keep wipes handy for painting." },
  { id: 9, name: "Michael", photo: "🎂", ageGroup: "Tweens (9–12)", interests: ["Birthdays", "People"], personality: "Uses birthdays as his superpower for connecting.", communication: "Let him ask about your birthday.", notes: "Tell him your birthday at the first meeting." },
  { id: 10, name: "Sara", photo: "📱", ageGroup: "Teens (13–17)", interests: ["Socializing", "Phone Numbers"], personality: "Friendly and outgoing.", communication: "Follow organization guidelines on contact info.", notes: "Kindly redirect personal number requests." },
  { id: 11, name: "Vera", photo: "🌸", ageGroup: "Tweens (9–12)", interests: ["Girly Activities", "Participating"], personality: "Eager to participate and very expressive.", communication: "Use gestures and visual cues.", notes: "Her face will tell you how she feels." },
  { id: 12, name: "Lee", photo: "🤗", ageGroup: "Young Kids (5–8)", interests: ["All Activities", "Physical Connection"], personality: "Very tactile and loves physical closeness.", communication: "Be physically present and responsive.", notes: "Full attention is the greatest gift." },
  { id: 13, name: "Diana", photo: "💬", ageGroup: "Teens (13–17)", interests: ["Texting", "Socializing", "Feeling Included"], personality: "A social butterfly who values inclusion.", communication: "Bring her into group conversations.", notes: "Ask, ‘Diana, what do you think?’" },
  { id: 14, name: "Ariella", photo: "🎶", ageGroup: "Tweens (9–12)", interests: ["Singing", "Jewish Songs"], personality: "Takes time to warm up, then opens up beautifully.", communication: "Patience and a calm voice are key.", notes: "Let her lead with music." },
];

const SEED_VOLUNTEERS = [
  { id: "v1", name: "Jessica M.", emoji: "👩", skills: ["Arts & Crafts", "Calm energy"], online: false, checkedIn: false, approved: true },
  { id: "v2", name: "Carlos R.", emoji: "👨", skills: ["Sports", "High energy"], online: false, checkedIn: true, approved: false },
  { id: "v3", name: "Taylor S.", emoji: "🧑", skills: ["Music", "Socializing"], online: false, checkedIn: false, approved: true },
  { id: "v4", name: "Priya K.", emoji: "👩", skills: ["Calm energy", "Creative"], online: false, checkedIn: false, approved: true },
  { id: "v5", name: "Jordan L.", emoji: "🧑", skills: ["Teens", "Conversation"], online: false, checkedIn: true, approved: false },
  { id: "v6", name: "Maria G.", emoji: "👩", skills: ["Young Kids", "Nurturing"], online: false, checkedIn: false, approved: true },
];

const INITIAL_PAIRINGS = [{ volunteerId: "v1", childId: 4 }, { volunteerId: "v1", childId: 5 }, { volunteerId: "v3", childId: 14 }, { volunteerId: "v5", childId: 3 }];

function scoreMatch(volunteer, child) {
  const skillText = volunteer.skills.join(" ").toLowerCase();
  const interestScore = child.interests.reduce((score, interest) => score + (skillText.includes(interest.toLowerCase().split(" ")[0]) ? 3 : 0), 0);
  const ageScore = volunteer.ageGroup === child.ageGroup || volunteer.ageGroup === "Any age" ? 4 : 0;
  return interestScore + ageScore;
}

function Logo() { return <div className="logo"><span className="logo-mark">◌</span><strong>Friendship <em>Circle</em></strong><small>BUDDY UP</small></div>; }
function Pill({ children, tone = "blue" }) { return <span className={`pill ${tone}`}>{children}</span>; }

function ChildModal({ child, onClose, canEdit, onEdit }) {
  if (!child) return null;
  return <div className="modal-backdrop" onClick={onClose}><section className="modal" onClick={e => e.stopPropagation()}>
    <button className="icon-button close" onClick={onClose} aria-label="Close">×</button>
    <div className="child-hero"><span>{child.photo}</span><div><p className="eyebrow">{child.ageGroup}</p><h2>{child.name}</h2></div></div>
    <div className="profile-grid"><div><b>Personality</b><p>{child.personality}</p></div><div><b>Communication</b><p>{child.communication}</p></div><div><b>Volunteer note</b><p>{child.notes}</p></div></div>
    <div className="pill-row">{child.interests.map(item => <Pill key={item}>{item}</Pill>)}</div>
    {canEdit && <button className="button primary full" onClick={() => onEdit(child)}>Edit profile</button>}
  </section></div>;
}

function Gate({ role, onSuccess, onBack }) {
  const [password, setPassword] = useState(""); const [error, setError] = useState("");
  const submit = () => password === PASSWORDS[role] ? onSuccess() : (setError("That password did not match."), setPassword(""));
  return <div className="gate"><Logo/><section className={`gate-card ${role.toLowerCase()}`}><span className="gate-icon">{role === "Staff" ? "▣" : role === "Parent" ? "⌂" : "✦"}</span><p className="eyebrow">Private access</p><h2>{role} portal</h2><p>Enter the access password to continue.</p><input autoFocus type="password" value={password} onChange={e => setPassword(e.target.value)} onKeyDown={e => e.key === "Enter" && submit()} placeholder="Access password" />{error && <div className="error">{error}</div>}<button className="button primary full" onClick={submit}>Enter portal</button><button className="button ghost full" onClick={onBack}>Back to preview</button></section></div>;
}

function VolunteerPortal({ children, volunteers, setVolunteers, pairings, onSelectChild }) {
  const [volunteerId, setVolunteerId] = useState("v1"); const volunteer = volunteers.find(v => v.id === volunteerId); const myPairings = pairings.filter(p => p.volunteerId === volunteerId).map(p => children.find(c => c.id === p.childId)).filter(Boolean);
  const toggleCheckIn = () => setVolunteers(prev => prev.map(v => v.id === volunteerId ? { ...v, checkedIn: !v.checkedIn, online: !v.online && v.approved } : v));
  return <div className="portal volunteer-portal"><div className="portal-header volunteer-head"><Logo/><div className="session-badge">Session today <span>● Live</span></div></div><div className="portal-body"><div className="select-wrap"><label>Your volunteer profile</label><select value={volunteerId} onChange={e => setVolunteerId(e.target.value)}>{volunteers.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></div><div className="welcome"><div><p className="eyebrow">Welcome back</p><h1>{volunteer.name}</h1><p>Ready to make a meaningful connection?</p></div><span className="avatar">{volunteer.emoji}</span></div><button className={`checkin ${volunteer.online ? "active" : ""}`} onClick={toggleCheckIn}>{volunteer.online ? "✓ Checked in for today" : volunteer.checkedIn && !volunteer.approved ? "Waiting for staff approval" : "Check in for today"}</button><div className="section-heading"><div><p className="eyebrow">Your buddy cards</p><h2>{myPairings.length ? "People to connect with" : "No pairings yet"}</h2></div><span className="count">{myPairings.length}</span></div>{myPairings.length ? <div className="card-list">{myPairings.map(child => <button className="buddy-card" key={child.id} onClick={() => onSelectChild(child)}><span className="buddy-emoji">{child.photo}</span><span><strong>{child.name}</strong><small>{child.ageGroup}</small><span className="pill-row">{child.interests.slice(0, 2).map(i => <Pill key={i}>{i}</Pill>)}</span></span><b>→</b></button>)}</div> : <div className="empty-state">Staff will add your buddy cards here after check-in.</div>}</div></div>;
}

function ParentPortal({ onAddChild }) {
  const [step, setStep] = useState(0); const [name, setName] = useState(""); const [ageGroup, setAgeGroup] = useState(AGE_GROUPS[1]); const [interests, setInterests] = useState([]);
  const options = ["Arts & crafts", "Music & singing", "Sports & outdoor play", "Socializing", "Quiet activities"];
  if (step === 2) return <div className="portal parent-portal"><div className="portal-header parent-head"><Logo/></div><div className="portal-body centered"><span className="success-icon">✓</span><p className="eyebrow">Profile received</p><h1>Thank you, {name}.</h1><p>Your child’s profile is with the Friendship Circle team. Staff will review it and create a thoughtful buddy match.</p><button className="button primary" onClick={() => { setStep(0); setName(""); setInterests([]); }}>Add another profile</button></div></div>;
  return <div className="portal parent-portal"><div className="portal-header parent-head"><Logo/><span className="secure-label">Staff-only information</span></div><div className="portal-body"><p className="eyebrow">Parent portal · {step === 0 ? "01 / 02" : "02 / 02"}</p><div className="progress"><span style={{ width: `${(step + 1) * 50}%` }} /></div>{step === 0 ? <><h1>Help us get to know your child.</h1><p className="lead">A few thoughtful details help our team create a comfortable first connection.</p><label>Child’s first name<input value={name} onChange={e => setName(e.target.value)} placeholder="First name" /></label><label>Age group<select value={ageGroup} onChange={e => setAgeGroup(e.target.value)}>{AGE_GROUPS.map(g => <option key={g}>{g}</option>)}</select></label><button className="button primary full" disabled={!name.trim()} onClick={() => setStep(1)}>Continue</button></> : <><h1>What lights them up?</h1><p className="lead">Choose everything that sounds like your child.</p><div className="option-list">{options.map(option => <button key={option} className={interests.includes(option) ? "option selected" : "option"} onClick={() => setInterests(prev => prev.includes(option) ? prev.filter(x => x !== option) : [...prev, option])}>{option}<span>{interests.includes(option) ? "✓" : "+"}</span></button>)}</div><div className="split-actions"><button className="button ghost" onClick={() => setStep(0)}>Back</button><button className="button primary" onClick={() => { onAddChild({ id: Date.now(), name, photo: "🌟", ageGroup, interests: interests.length ? interests : ["Social Connection"], personality: "Parent-submitted profile.", communication: "See parent notes.", notes: "New participant; get to know them!", addedByParent: true }); setStep(2); }}>Submit profile</button></div></>}</div></div>;
}

function StaffPortal({ children, setChildren, volunteers, setVolunteers, pairings, setPairings, onSelectChild }) {
  const [view, setView] = useState("pairings"); const [editing, setEditing] = useState(null); const [newName, setNewName] = useState("");
  const online = volunteers.filter(v => v.online && v.approved); const pending = volunteers.filter(v => v.checkedIn && !v.approved); const unpaired = children.filter(c => !pairings.some(p => p.childId === c.id));
  const approve = id => setVolunteers(prev => prev.map(v => v.id === id ? { ...v, approved: true, online: true } : v));
  const saveChild = () => { if (!newName.trim()) return; setChildren(prev => prev.map(c => c.id === editing.id ? { ...c, name: newName.trim() } : c)); setEditing(null); };
  return <div className="portal staff-portal"><div className="portal-header staff-head"><Logo/><div><p className="eyebrow">Staff dashboard</p><h2>Session command center</h2></div><span className="online-dot">{online.length} online</span></div><div className="portal-body"><div className="stats"><div><b>{online.length}</b><small>Online</small></div><div><b>{pending.length}</b><small>Pending</small></div><div><b>{new Set(pairings.map(p => p.childId)).size}</b><small>Paired</small></div><div><b>{unpaired.length}</b><small>Unpaired</small></div></div>{pending.length > 0 && <div className="notice"><b>Pending approvals</b>{pending.map(v => <div className="approval" key={v.id}><span>{v.emoji} {v.name}</span><button onClick={() => approve(v.id)}>Approve</button></div>)}</div>}<nav className="view-tabs">{[["pairings", "Pairings"], ["roster", "Roster"], ["children", "Children"]].map(([id, label]) => <button className={view === id ? "active" : ""} key={id} onClick={() => setView(id)}>{label}</button>)}</nav>{view === "pairings" && <div className="staff-list"><h2>This session’s pairings</h2>{volunteers.map(v => { const buddies = pairings.filter(p => p.volunteerId === v.id).map(p => children.find(c => c.id === p.childId)).filter(Boolean); return buddies.length ? <div className="pairing-row" key={v.id}><b>{v.emoji} {v.name}</b>{buddies.map(c => <button key={c.id} onClick={() => onSelectChild(c)}>{c.photo} {c.name} <span>→</span></button>)}</div> : null; })}</div>}{view === "roster" && <div className="staff-list"><h2>Volunteer roster</h2>{volunteers.map(v => <div className="roster-row" key={v.id}><span>{v.emoji}</span><b>{v.name}</b><small>{v.skills.join(" · ")}</small><i className={v.online ? "online" : ""}>{v.online ? "Online" : "Offline"}</i></div>)}</div>}{view === "children" && <div className="staff-list"><div className="section-heading"><h2>Child database</h2><span>{children.length} profiles</span></div>{children.map(c => <div className="roster-row" key={c.id}><span>{c.photo}</span><b>{c.name}</b><small>{c.ageGroup}</small><button onClick={() => { setEditing(c); setNewName(c.name); }}>Edit</button></div>)}</div>}</div>{editing && <div className="modal-backdrop"><section className="modal compact"><h2>Edit child profile</h2><label>Name<input value={newName} onChange={e => setNewName(e.target.value)} /></label><div className="split-actions"><button className="button ghost" onClick={() => setEditing(null)}>Cancel</button><button className="button primary" onClick={saveChild}>Save</button></div></section></div>}</div>;
}

export default function App() {
  const [view, setView] = useState("preview"); const [children, setChildren] = useState(SEED_CHILDREN); const [volunteers, setVolunteers] = useState(SEED_VOLUNTEERS); const [pairings, setPairings] = useState(INITIAL_PAIRINGS); const [selected, setSelected] = useState(null); const [unlocked, setUnlocked] = useState({});
  const nav = [{ id: "preview", label: "Preview" }, { id: "volunteer", label: "Volunteer" }, { id: "staff", label: "Staff" }, { id: "parent", label: "Parent" }];
  const portal = type => !unlocked[type] ? <Gate role={type[0].toUpperCase() + type.slice(1)} onSuccess={() => setUnlocked(p => ({ ...p, [type]: true }))} onBack={() => setView("preview")} /> : type === "volunteer" ? <VolunteerPortal {...{ children, volunteers, setVolunteers, pairings }} onSelectChild={setSelected} /> : type === "staff" ? <StaffPortal {...{ children, setChildren, volunteers, setVolunteers, pairings, setPairings }} onSelectChild={setSelected} /> : <ParentPortal onAddChild={child => setChildren(prev => [...prev, child])} />;
  return <main><header className="topbar"><Logo/><nav>{nav.map(item => <button className={view === item.id ? "active" : ""} key={item.id} onClick={() => setView(item.id)}>{item.label}</button>)}</nav></header>{view === "preview" ? <Preview children={children} onSelectChild={setSelected} onNavigate={setView} /> : portal(view)}<ChildModal child={selected} onClose={() => setSelected(null)} canEdit={view === "staff"} onEdit={child => setSelected(null)} /></main>;
}

function Preview({ children, onSelectChild, onNavigate }) {
  const [query, setQuery] = useState(""); const [age, setAge] = useState("All"); const filtered = useMemo(() => children.filter(c => (age === "All" || c.ageGroup === age) && `${c.name} ${c.interests.join(" ")}`.toLowerCase().includes(query.toLowerCase())), [children, age, query]);
  return <div className="preview"><section className="intro"><div><p className="eyebrow">Sun Circle program · 2026</p><h1>Small moments.<br/><em>Big belonging.</em></h1><p>Buddy Up helps volunteers, families, and staff make every connection feel intentional.</p><button className="button primary" onClick={() => onNavigate("volunteer")}>Open volunteer portal <span>→</span></button></div><div className="intro-art"><span>✦</span><span>☼</span><span>◌</span></div></section><section className="directory"><div className="section-heading"><div><p className="eyebrow">The circle</p><h2>Meet the children</h2></div><span>{filtered.length} profiles</span></div><div className="filters"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search names or interests" />{["All", ...AGE_GROUPS].map(g => <button className={age === g ? "active" : ""} key={g} onClick={() => setAge(g)}>{g === "All" ? "All ages" : g.split(" ")[0]}</button>)}</div><div className="children-grid">{filtered.map(c => <button className="child-card" key={c.id} onClick={() => onSelectChild(c)}><span className="child-photo">{c.photo}</span><span><strong>{c.name}</strong><small>{c.ageGroup}</small><span className="pill-row">{c.interests.slice(0, 2).map(i => <Pill key={i}>{i}</Pill>)}</span></span><b>↗</b></button>)}</div></section></div>;
}
